[pipeline]
# Ruta al CSV original
input_csv = "/home/alumnos/luciiaa/airflow/dags/tripadvisor_european_restaurants.csv"
# Ruta donde se guardará el resultado
output_csv = "/home/alumnos/luciiaa/airflow/dags/resultados_limpios.parquet"

[kafka]
bootstrap_servers = "localhost:9092"
topic = "tripadvisor"

